# Generated by Django 5.2.4 on 2025-07-22 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('material', 'Material'), ('labor', 'Mano de Obra'), ('equipment', 'Equipo'), ('subcontract', 'Subcontrato'), ('transport', 'Transporte'), ('overhead', 'Gastos Generales')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('overhead_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de overhead aplicado a este tipo de recurso', max_digits=5)),
            ],
            options={
                'verbose_name': 'Tipo de Recurso',
                'verbose_name_plural': 'Tipos de Recursos',
            },
        ),
        migrations.CreateModel(
            name='ProjectEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('client', models.CharField(max_length=200, verbose_name='Cliente')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('estimate_date', models.DateField(verbose_name='Fecha de Estimación')),
                ('validity_days', models.IntegerField(default=30, verbose_name='Validez (días)')),
                ('site_factor', models.DecimalField(decimal_places=3, default=1.0, help_text='Factor por condiciones específicas del sitio', max_digits=5, verbose_name='Factor de Sitio')),
                ('season_factor', models.DecimalField(decimal_places=3, default=1.0, help_text='Factor por época del año', max_digits=5, verbose_name='Factor Estacional')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('executed', 'Ejecutado')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estimación de Proyecto',
                'verbose_name_plural': 'Estimaciones de Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('unit', models.CharField(help_text='ej: m3, kg, hora, día', max_length=20, verbose_name='Unidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Unitario')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_analysis.resourcetype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitPriceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Análisis')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descripción del Servicio')),
                ('unit', models.CharField(help_text='ej: m2, m3, pieza, global', max_length=20, verbose_name='Unidad')),
                ('performance_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='Factor que afecta la productividad (1.0 = rendimiento estándar)', max_digits=8, verbose_name='Factor de Rendimiento')),
                ('difficulty_factor', models.DecimalField(decimal_places=3, default=1.0, help_text='Factor por condiciones especiales o dificultad del trabajo', max_digits=5, verbose_name='Factor de Dificultad')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Margen de Ganancia (%)')),
                ('administrative_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Gastos Administrativos (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_analysis.servicecategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Precio Unitario',
                'verbose_name_plural': 'Análisis de Precios Unitarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Se toma del análisis, pero puede ser ajustado', max_digits=12, verbose_name='Precio Unitario')),
                ('description', models.TextField(blank=True, verbose_name='Descripción Específica')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_items', to='pricing_analysis.projectestimate')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_analysis.unitpriceanalysis', verbose_name='Análisis')),
            ],
            options={
                'verbose_name': 'Item de Estimación',
                'verbose_name_plural': 'Items de Estimación',
            },
        ),
        migrations.CreateModel(
            name='UnitPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Se llena automáticamente del recurso, pero puede ser modificado', max_digits=12, verbose_name='Costo Unitario')),
                ('efficiency', models.DecimalField(decimal_places=3, default=1.0, help_text='Factor de eficiencia específico para este recurso en este análisis', max_digits=5, verbose_name='Eficiencia')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing_analysis.unitpriceanalysis')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_analysis.resource', verbose_name='Recurso')),
            ],
            options={
                'verbose_name': 'Item de Análisis',
                'verbose_name_plural': 'Items de Análisis',
                'unique_together': {('analysis', 'resource')},
            },
        ),
    ]
