# Generated by Django 5.2.4 on 2025-07-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('sales', 'Reporte de Ventas'), ('products', 'Reporte de Productos'), ('customers', 'Reporte de Clientes'), ('finances', 'Reporte Financiero'), ('inventory', 'Reporte de Inventario')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
