# Generated by Django 5.2.4 on 2025-10-03 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100, verbose_name='ID de Campaña')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Campaña')),
                ('objective', models.CharField(blank=True, max_length=100, verbose_name='Objetivo')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('daily_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Presupuesto Diario')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Presupuesto Total')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('ended', 'Finalizada'), ('draft', 'Borrador')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaña de Marketing',
                'verbose_name_plural': 'Campañas de Marketing',
            },
        ),
        migrations.CreateModel(
            name='MarketingBudgetOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_action', models.CharField(choices=[('increase_budget', 'Aumentar Presupuesto'), ('decrease_budget', 'Disminuir Presupuesto'), ('pause_campaign', 'Pausar Campaña'), ('redistribute_budget', 'Redistribuir Presupuesto'), ('change_bidding', 'Cambiar Estrategia de Puja')], max_length=30, verbose_name='Acción Recomendada')),
                ('current_budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Presupuesto Actual')),
                ('recommended_budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Presupuesto Recomendado')),
                ('expected_improvement', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Mejora Esperada (%)')),
                ('reasoning', models.TextField(verbose_name='Razonamiento')),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nivel de Confianza (%)')),
                ('implemented', models.BooleanField(default=False, verbose_name='Implementado')),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('implemented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Implementado por')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_analytics.marketingcampaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Optimización de Presupuesto',
                'verbose_name_plural': 'Optimizaciones de Presupuesto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('performance', 'Rendimiento'), ('audience', 'Audiencia'), ('creative', 'Creativos'), ('budget', 'Presupuesto'), ('optimization', 'Optimización'), ('trend', 'Tendencia')], max_length=20, verbose_name='Tipo de Insight')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('trigger_metrics', models.JSONField(default=dict, verbose_name='Métricas Disparadoras')),
                ('recommended_actions', models.JSONField(default=list, verbose_name='Acciones Recomendadas')),
                ('estimated_impact', models.TextField(blank=True, verbose_name='Impacto Estimado')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Puntuación de Confianza (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='Reconocido')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reconocido por')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing_analytics.marketingcampaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Insight de Marketing',
                'verbose_name_plural': 'Insights de Marketing',
                'ordering': ['-created_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='MarketingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Plataforma')),
                ('platform_type', models.CharField(choices=[('google_ads', 'Google Ads'), ('instagram', 'Instagram Business'), ('facebook_ads', 'Facebook Ads'), ('linkedin_ads', 'LinkedIn Ads'), ('tiktok_ads', 'TikTok Ads'), ('youtube_ads', 'YouTube Ads')], max_length=20, verbose_name='Tipo de Plataforma')),
                ('api_key', models.TextField(help_text='Clave API encriptada', verbose_name='API Key')),
                ('api_secret', models.TextField(blank=True, verbose_name='API Secret')),
                ('access_token', models.TextField(blank=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='Refresh Token')),
                ('account_id', models.CharField(blank=True, max_length=100, verbose_name='Account ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización')),
                ('sync_frequency_hours', models.IntegerField(default=24, verbose_name='Frecuencia de Sincronización (horas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plataforma de Marketing',
                'verbose_name_plural': 'Plataformas de Marketing',
                'unique_together': {('platform_type', 'account_id')},
            },
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_analytics.marketingplatform', verbose_name='Plataforma'),
        ),
        migrations.CreateModel(
            name='MarketingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('impressions', models.BigIntegerField(default=0, verbose_name='Impresiones')),
                ('reach', models.BigIntegerField(default=0, verbose_name='Alcance')),
                ('unique_users', models.BigIntegerField(default=0, verbose_name='Usuarios Únicos')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clics')),
                ('likes', models.IntegerField(default=0, verbose_name='Me Gusta')),
                ('comments', models.IntegerField(default=0, verbose_name='Comentarios')),
                ('shares', models.IntegerField(default=0, verbose_name='Compartidos')),
                ('saves', models.IntegerField(default=0, verbose_name='Guardados')),
                ('conversions', models.IntegerField(default=0, verbose_name='Conversiones')),
                ('leads', models.IntegerField(default=0, verbose_name='Leads')),
                ('purchases', models.IntegerField(default=0, verbose_name='Compras')),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gasto')),
                ('cost_per_click', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Costo por Clic (CPC)')),
                ('cost_per_impression', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Costo por Mil Impresiones (CPM)')),
                ('cost_per_conversion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo por Conversión')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos')),
                ('additional_metrics', models.JSONField(blank=True, default=dict, verbose_name='Métricas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='marketing_analytics.marketingcampaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Métrica de Marketing',
                'verbose_name_plural': 'Métricas de Marketing',
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='marketingcampaign',
            unique_together={('platform', 'campaign_id')},
        ),
        migrations.CreateModel(
            name='MarketingAudienceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('age_groups', models.JSONField(default=dict, verbose_name='Grupos de Edad')),
                ('gender_distribution', models.JSONField(default=dict, verbose_name='Distribución por Género')),
                ('top_locations', models.JSONField(default=list, verbose_name='Principales Ubicaciones')),
                ('interests', models.JSONField(default=list, verbose_name='Intereses')),
                ('device_types', models.JSONField(default=dict, verbose_name='Tipos de Dispositivo')),
                ('peak_hours', models.JSONField(default=dict, verbose_name='Horas Pico')),
                ('engagement_by_content_type', models.JSONField(default=dict, verbose_name='Engagement por Tipo de Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_analytics.marketingplatform', verbose_name='Plataforma')),
            ],
            options={
                'verbose_name': 'Insight de Audiencia',
                'verbose_name_plural': 'Insights de Audiencia',
                'ordering': ['-date'],
                'unique_together': {('platform', 'date')},
            },
        ),
    ]
